### ISSUE TITLE
java.lang.ClassCastException: org.eclipse.ec4j.core.model.PropertyType$ParsedValue cannot be cast to org.eclipse.ec4j.core.model.PropertyType$IndentStyleValue

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/ec4j#65]
When https://github.com/angelozerr/ec4e/blob/master/org.eclipse.ec4e/src/main/java/org/eclipse/ec4e/internal/EditorConfigPreferenceStore.java#L63 is executed, I have this error:

```
java.lang.ClassCastException: org.eclipse.ec4j.core.model.PropertyType$ParsedValue cannot be cast to org.eclipse.ec4j.core.model.PropertyType$IndentStyleValue
	at org.eclipse.ec4e.internal.EditorConfigPreferenceStore.applyConfig(EditorConfigPreferenceStore.java:63)
	at org.eclipse.ec4e.internal.ApplyEditorConfig.applyConfig(ApplyEditorConfig.java:39)
	at org.eclipse.ec4e.internal.EditorTracker.editorOpened(EditorTracker.java:175)
```

If you have time to see this problem @ppalaga it should b ecool, otherwise I will do it, thanks

**Comment by ppalaga** [comment]
Nota bene: never commit anything without unit tests :/

**Comment by angelozerr** [comment]
Nota bene: never accept PR without trying it:)
